<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class HardwareTableSeeder extends Seeder
{
    public function run()
    {
        $hardwareData = [
            [
                'id' => 1,
                'name' => 'Aspire TC-1785 500W 14th Gen Core i7',
                'description' => 'Intel® Core™ i7-14700 processor (20 Cores 28 Threads 2.1GHz up to 5.4GHz, 33MB Intel® Smart Cache) 8 GB DDR5 4800MHz UDIMM Up to 32 GB of Dual-channel DDR5. 256 GB M.2 2280 PCI-E SSD 1 TB 3.5-inch 7200 RPM. Windows ® 11 Home SL with MS Office for Home & S',
                'category' => 'computer',
                'image' => 'pc1.png',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 2,
                'name' => 'ALL-IN-ONE Aspire C24-195ES New Core Ultra 5 CPU',
                'description' => 'Aspire C24-195ES New Core Ultra 5 CPU 8GB 512GB SSD, Intel® Graphics, with Office for Home and Student. Intel® Core™ Ultra 5 processor 125U (up to 4.3 GHz, 12 MB cache, 2 P-core/8 E-core/2 LPE-core/14 thread, 15 W, Intel® Graphics) Windows ® 11 Home SL wi',
                'category' => 'computer',
                'image' => 'pc2.png',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 3,
                'name' => 'Asus Desktop AIO (Black) 27" non-touch',
                'description' => 'Asus Desktop AIO (Black) 27" non-touch/ Intel Core i7-150U/ 16GB DDR5/ Shared/ 1TB SSD/ 120W/ Win11 home/ H&S / 3-3-3',
                'category' => 'computer',
                'image' => 'pc3.png',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 4,
                'name' => 'Acer Swift Go',
                'description' => 'SFG14-71T-72QV 📌Acer Swift Go Intel Evo Thin & Light Premium Laptop 14" Touchscreen Display, Intel Core i7-1355U, Intel Iris Xe Graphics, 16GB LPDDR5, 512GB SSD, Windows 11 Home',
                'category' => 'laptop',
                'image' => 'lp1.png',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 5,
                'name' => 'ASUS Vivobook 16” Laptop computer',
                'description' => 'F1605ZA-WS74 📌ASUS Vivobook 16” PC Laptop, Intel Core i7-1255U, 16GB RAM, 512GB SSD, Intel Iris Xe Graphics, Windows 11 Home - Black',
                'category' => 'laptop',
                'image' => 'lp2.png',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 6,
                'name' => 'ASUS ROG Flow X13',
                'description' => 'GV302XA-X13.R9512 📌ASUS ROG Flow X13 13.4" Touchscreen Gaming Laptop FHD, AMD Ryzen 9 7940HS, 16GB Memory, 512GB SSD, Windows 11 Home - Off Black',
                'category' => 'laptop',
                'image' => 'lp3.png',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 7,
                'name' => 'Dell Inspiron 15 3520',
                'description' => '8JTD9 📌Dell Inspiron 15 3520, i3-1215U, 8GB, 512GB SSD, UHD Graphics, Webcam, BT, 15.6”(1920X1080)W11, Carbon Black',
                'category' => 'laptop',
                'image' => 'lp4.png',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 8,
                'name' => 'Apple Ipad 9th Gen, 10.2 inch',
                'description' => 'MK2K3PP/A 📌Apple Ipad 9th Gen, 10.2" Retina Display, A13 Bionic Chip, 64GB Internal Storage, 8MP Wide Rear Camera, 12MP Ultrawide Front Camera, IpadOS',
                'category' => 'laptop',
                'image' => 'lp5.png',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 9,
                'name' => 'Sangfor HCI Server',
                'description' => 'Hyperconverged infrastructure (HCI), or hyper converged software, is a unified system of data storage. As opposed to a traditional system, hyper-converged software combines storage, computing, networking, and management all under one roof.',
                'category' => 'server',
                'image' => 'sv1.png',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 10,
                'name' => 'RG-EW1200G PRO 1300M Dual-band Gigabit Wireless Router',
                'description' => 'High-performance Gigabit routing 1267M Dual-Band Integration offering low interference and fast internet speed Optimize 2.4G to increase the limit of smart terminal connections MU-MIMO Offers higher transmission efficiency professional RF design multiples the coverage distance Exclusive Reyee Mesh Technology Enables Zero-configuration Networking for multi-devices. Wireless specifications - 2.4GHz 2*2: Maximum rate 400mMbps; 5Ghz 2*2: Maximum rate 8687Mbps Antenna: External 6dBi non-removable omnidirectional antennas Support 80211a/b/g/n/ac/ac Wave2, MU-MIMO Frequency band: Independent 2.4GHz and 5GHz modules, supporting dual frequency integration',
                'category' => 'router',
                'image' => 'rt1.png',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 11,
                'name' => 'Sangfor Network Secure Firewall',
                'description' => 'Sangfor Network Secure (previously known as Sangfor NGAF) is the world’s first Next-Generation Firewall (NGFW) that combines AI Technology, Cloud Threat Intelligence, NG-WAF, IoT Security, and SoC Lite.',
                'category' => 'firewall',
                'image' => 'fw1.png',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 12,
                'name' => 'AWS CLOUD SERVICES',
                'description' => 'Amazon Web Services has been providing world-leading cloud technologies that help any organization and any individual build solutions to transform industries, communities, and lives for the better. Whether they are entrepreneurs launching new businesses, established companies reinventing themselves, non-profits working to advance their missions, or governments and cities seeking to serve their citizens more effectively—our customers trust AWS with their livelihoods, their goals, their ideas, and their data.',
                'category' => 'cloud',
                'image' => 'cl1.png',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 13,
                'name' => 'AWS Architecture for hosting Web Applications',
                'description' => 'Taking a closer look at how to architect an infrastructure on AWS to host Web Applications',
                'category' => 'cloud',
                'image' => 'cl2.png',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 14,
                'name' => 'EPSON TM-T88VI Thermal Receipt Printer',
                'description' => 'Product Code: C31CE94163 Print Method: Thermal Line printing Interface: USB+Ethernet+Parallel Print Speed: Max. 360 mm/sec Dot density: 180 x 180 dpi Paper: Width x Diameter: 79.5 ± 0.5 mm x 83.0 / 57.5 ± 0.5 x 83.0 mm Thickness: 0.048 mm to 0.08 mm',
                'category' => 'printer',
                'image' => 'ps1.png',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 15,
                'name' => 'Epson TM-U220B POS Printer',
                'description' => '9-pin serial impact dot matrix 4.7 lps (at 40 columns, 16 cpi), 6.0 lps (at 30 columns, 16 cpi) Easy Operation -USB connection, Power Supply: AC adapter Supply Voltage: DC +24 V ± 7%',
                'category' => 'printer',
                'image' => 'ps2.png',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 16,
                'name' => 'HPRT TP80K POS Thermal Receipts Printer',
                'description' => 'Print Method: Direct Thermal Resolution: 203dpi Print Width: 80mm (576 dots) Paper Loading: Up Loading Paper Width: 79.5 +- 0.5mm / 57.5 +- 0.5mm Auto Cutter: Partial Cut Interface: USB + Serial + Ethernet Power：24V/5A',
                'category' => 'printer',
                'image' => 'ps3.png',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 17,
                'name' => 'HPRT Barcode Scanner N160',
                'description' => 'Symbologies: 1D/2D Image Sensor: CMOS Pixel: 1280x1080 Aiming: Red Line Scan Notification: Beep, LED Indicator Anti-Shock Ability: 1.5m Interface: USB Power: 5VDC+-10%',
                'category' => 'printer',
                'image' => 'ps4.png',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 18,
                'name' => 'Olivetti PR2E passbook Printer',
                'description' => 'Olivetti PR2 plus is a specialized printer for multifunctional front-office applications. It is capable of printing on slips, single-sheet and on passbooks. Interface is dual serial, one USB, and one parallel port.',
                'category' => 'printer',
                'image' => 'ps5.png',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 19,
                'name' => 'ZEBRA ZC300 ID Card Printer',
                'description' => 'ZEBRA ZC300 ID Card Printer Part no. : ZC32-000C000AP00 Print Capabilities : Single & Dual Sided Card Thickness : 10 to 40 mil Print Method : Direct to Card Print Speed : 140 Color cph / 450 mono cph Memory : 2 GB flash Color : Includes : Power Supply, USB Printer Cable and User Training Added Features : USB & Ethernet, Windows Driver Zebra PVC Cards Part Nos: 104523-111 Desc: Zebra white PVC cards, 30 mil (500 cards) ZC300 Ribbon Part Nos: 800300-252AP Ribbon, Color-YMCKO, 58mmx148m(2.28inx485ft), 300 Images, ZC300, RoAOB',
                'category' => 'printer',
                'image' => 'ps6.png',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 20,
                'name' => 'SMART MOBILE POS',
                'description' => 'Designed for convenience and functionality A lightweight and portable device that can be used to manage accounts, and settle payments and deposits.',
                'category' => 'printer',
                'image' => 'ps7.png',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 21,
                'name' => 'HOLOWITS CCTV CAMERAS',
                'description' => 'The HOLOWITS AI camera and sensors work perfectly with Milestone\'s open platform software for data processing to give customers a complete and reliable security solution.',
                'category' => 'cctv',
                'image' => 'cm1.png',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 22,
                'name' => 'Starlink',
                'description' => 'Engage in activities that have historically not been possible with satellite internet. Made possible via the world’s largest constellation of highly advanced satellites operating in a low orbit around the Earth. Designed for Self-install. No lock-in contract. Subscription Plan: Residential - Fixed location, unlimited internet. Php2,700.00 / PLAN Roam - In motion use. Countryside Coverage Php4,100.00',
                'category' => 'wifi',
                'image' => 'wifi1.png',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 23,
                'name' => 'ZKTECO K14 Time Attendance Biometric',
                'description' => 'Specifications: 3,000 User Capacity 3,000 Fingerprint Capacity 1,000 RFID Capacity 100,000 Logs Capacity 2.8-inches TFT Screen Display USB Host, TCP/IP Communications',
                'category' => 'TAB',
                'image' => 'bio1.png',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 24,
                'name' => 'OrangePay Plus HR management System',
                'description' => 'Stand alone system A complete paperless HR Management Solution for SMBs and Enterprise Businesses. Complete ease in managing employee info and payroll computation Convenient employee access to their info and payslip Can be connected to ZKTECO K14 biometric device via API - Free',
                'category' => 'TAB',
                'image' => 'bio2.png',
                'created_at' => null,
                'updated_at' => null,
            ],
        ];

        foreach ($hardwareData as $data) {
            DB::table('hardware')->insert($data);
        }
    }
}