<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ImagedsTableSeeder extends Seeder
{
    public function run()
    {
        $imagedsData = [
            [
                'id' => 1,
                'name' => 'Dalaguete Government Employees Multipurpose Cooperative',
                'image' => '11.jpg',
                'category' => 'Government & Employee',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'name' => 'Police Regional Office XI Multi-Purpose Cooperative',
                'image' => '19.jpg',
                'category' => 'Police and Military-Related',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'name' => 'Tekton Entre Multipurpose Cooperative',
                'image' => '20.png',
                'category' => 'Government & Employee',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'name' => '205th THW Multi-Purpose Cooperative',
                'image' => '205th THW MPC.png',
                'category' => 'Police and Military-Related',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'name' => 'Catholic Servants of Christ Community Multi-Purpose Cooperative',
                'image' => '315213295_559202782877302_247834250035216991_n.jpg',
                'category' => 'Religious and Parish-Based',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'name' => 'Eastland Property Ventures Inc.',
                'image' => '6.jpg',
                'category' => 'Corporations and Non-Cooperative',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'name' => 'Abucay Multipurpose Cooperative',
                'image' => 'ABUCAY MPC.jpg',
                'category' => 'Community and Farmers',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'name' => 'Agdao Multipurpose Cooperative',
                'image' => 'AGDAO MPC.png',
                'category' => 'Community and Farmers',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9,
                'name' => 'Alagad Katikista Leaders Multi - Purpose Cooperative',
                'image' => 'ALKALEAD.png',
                'category' => 'General Multipurpose',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 10,
                'name' => 'Bukidnon Community Cooperative',
                'image' => 'BCC.png',
                'category' => 'General Multipurpose',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 11,
                'name' => 'BOHECO II Employees Multi-Purpose Cooperative',
                'image' => 'BOHECO II MPC.jpg',
                'category' => 'Corporate and Employee',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 12,
                'name' => 'Bokod Sulphur Spring Multipurpose Cooperative',
                'image' => 'BSSMClogo.png',
                'category' => 'Community and Farmers',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 13,
                'name' => 'Camsur Multi-Purpose Cooperative',
                'image' => 'CAMSUR.jpeg',
                'category' => 'General Multipurpose',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 14,
                'name' => 'COA Employees Multi-Purpose Cooperative of Region Eight',
                'image' => 'COA CARE.png',
                'category' => 'Government and Employee',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 15,
                'name' => 'Damayan sa Cavite Community Multi-Purpose',
                'image' => 'DACCOMPC.jpg',
                'category' => 'Community and Farmers',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 16,
                'name' => 'Danao Employees Multi-Purpose Cooperative',
                'image' => 'DAEMCO.jpg',
                'category' => 'General Multipurpose',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 17,
                'name' => 'DSE BSP Credit Cooperative',
                'image' => 'DSEBSPCC.png',
                'category' => 'General Multipurpose',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 18,
                'name' => 'First Consolidated Cooperative Along Tañon Seaboards',
                'image' => 'FCCT Logo.png',
                'category' => 'General Multipurpose',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 19,
                'name' => 'Jagna Multi-Purpose Cooperative',
                'image' => 'JMPC.jpg',
                'category' => 'General Multipurpose',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 20,
                'name' => 'King\'s Multi-Purpose Cooperative',
                'image' => 'KMPC.jpg',
                'category' => 'General Multipurpose',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 21,
                'name' => 'Luxid Rotary Micro Finance and Credit Cooperative',
                'image' => 'LUXID1.jpg',
                'category' => 'General Multipurpose',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 22,
                'name' => 'Mandaue City Public Market Vendors Multi-Purpose Cooperative',
                'image' => 'MAVENCO.jpg',
                'category' => 'Market Vendors and Small Business',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 23,
                'name' => 'Metro Zambales Multi-Purpose Cooperative',
                'image' => 'MZMPC.jpg',
                'category' => 'General Multipurpose',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 24,
                'name' => 'Panabo Multi-Purpose Cooperative',
                'image' => 'PANABO MPC.png',
                'category' => 'General Multipurpose',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 25,
                'name' => 'Piwong Multipurpose Cooperative',
                'image' => 'PIWONG LOGO.jpg',
                'category' => 'General Multipurpose',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 26,
                'name' => 'Santa Rosa City Employees Multi-Purpose Cooperative',
                'image' => 'Picture1.jpg',
                'category' => 'Government and Employee',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 27,
                'name' => 'Salvacion Farmers Development Cooperative',
                'image' => 'SAFADECO.png',
                'category' => 'Community and Farmers',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 28,
                'name' => 'Sta. Ana Multipurpose Cooperative',
                'image' => 'SAMULCO.png',
                'category' => 'General Multipurpose',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 29,
                'name' => 'Sacred Heart Development Cooperative',
                'image' => 'SHCDC.jpg',
                'category' => 'Religious and Parish-Based',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 30,
                'name' => 'St. Joseph Financing Corporation',
                'image' => 'SJFC1.jpg',
                'category' => 'Corporations and Non-Cooperative',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 31,
                'name' => 'Agricooph Federation',
                'image' => 'agricoop.png',
                'category' => 'Community and Farmers',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 32,
                'name' => 'Aguipo Coconut Farmers Multipurpose Cooperative',
                'image' => 'aguipo2.png',
                'category' => 'Community and Farmers',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 33,
                'name' => 'Atlas Mining Community Handicapped Association',
                'image' => 'amchalogo.jpg',
                'category' => 'Community and Farmers',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 34,
                'name' => 'Amlan LGU Community Multipurpose Cooperative',
                'image' => 'alcomcologo.png',
                'category' => 'Community and Farmers',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 35,
                'name' => 'Baggak Multi-Purpose Cooperative',
                'image' => 'baggakmpc.jpg',
                'category' => 'Community and Farmers',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 36,
                'name' => 'Bagtic Masagana Multi-Purpose Cooperative',
                'image' => 'bagticlogo.jpg',
                'category' => 'Community and Farmers',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 37,
                'name' => 'Basey 1 District Multipurpose Cooperative',
                'image' => 'basey1.png',
                'category' => 'Community and Farmers',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 38,
                'name' => 'Bayanihan Millenium Multi-Purpose Cooperative',
                'image' => 'bayanihanmmpc.jpg',
                'category' => 'Community and Farmers',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 39,
                'name' => 'Baug CARP Beneficiaries Multi Purpose Cooperative',
                'image' => 'bcbmpc.jpg',
                'category' => 'Community and Farmers',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 40,
                'name' => 'Bohol Provincial Employees Cooperative',
                'image' => 'bopelogo.jpg',
                'category' => 'Government and Employee',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 41,
                'name' => 'BOWSSCO Multipurpose Cooperative',
                'image' => 'bowwscologo.jpg',
                'category' => 'General Multipurpose',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 42,
                'name' => 'Benguet State University and Community Multipurpose Cooperative',
                'image' => 'bsulogo.png',
                'category' => 'University/School-Based',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 43,
                'name' => 'Campangga Alayon Multi-Purpose Cooperative',
                'image' => 'campco.jpg',
                'category' => 'Community and Farmers',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 44,
                'name' => 'Carmen Samahang Nayon Multi-Purpose Cooperative',
                'image' => 'carmenlogo3.jpg',
                'category' => 'Community and Farmers',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 45,
                'name' => 'Cebu Market Vendors Multipurpose Cooperative',
                'image' => 'cemvedco.jpg',
                'category' => 'Market Vendors and Small Business',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 46,
                'name' => 'CEV Credit Cooperative',
                'image' => 'cevcc.png',
                'category' => 'General Multipurpose',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 47,
                'name' => 'Cebu CFI Community Cooperative',
                'image' => 'cfilogo3.png',
                'category' => 'Community and Farmers',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 48,
                'name' => 'CLC Lending Corporation',
                'image' => 'clclogo.png',
                'category' => 'General Multipurpose',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 49,
                'name' => 'Community Multipurpose Cooperative of Paknaan',
                'image' => 'cmpclogo.png',
                'category' => 'Community and Farmers',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 50,
                'name' => 'COA Prime Investors Multi-Purpose Cooperative, Inc.',
                'image' => 'coapimupco.png',
                'category' => 'Government and Employee',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 51,
                'name' => 'Compostela Market Vendors Multipurpose Cooperative',
                'image' => 'comavemcologo.jpg',
                'category' => 'Market Vendors and Small Business',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 52,
                'name' => 'USP Multi Purpose Cooperative',
                'image' => 'cooptoday.jpeg',
                'category' => 'General Multipurpose',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 53,
                'name' => 'Candelaria Multi-Purpose Cooperative',
                'image' => 'cpmclogo.jpg',
                'category' => 'General Multipurpose',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 54,
                'name' => 'Cuta Farmers Multi-Purpose Cooperative',
                'image' => 'cutalogo.jpg',
                'category' => 'Community and Farmers',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 55,
                'name' => 'Cebu Vendors Credit Cooperative',
                'image' => 'cvcco.png',
                'category' => 'Market Vendors and Small Business',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 56,
                'name' => 'Danao Agrarian Reform Cooperative',
                'image' => 'darclogo.png',
                'category' => 'Community and Farmers',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 58,
                'name' => 'Dole Community Multi-Purpose Cooperative',
                'image' => 'dcompc.jpg',
                'category' => 'General Multipurpose',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 59,
                'name' => 'Equitable PCIB Employees Credit Cooperative',
                'image' => 'epciblogo.png',
                'category' => 'Corporate and Employee',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 60,
                'name' => 'Fairchild Cebu Community Multi-Purpose Cooperative',
                'image' => 'fairchildcooplogo3.png',
                'category' => 'General Multipurpose',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 61,
                'name' => 'Garcilot Food (Five Star Manok)',
                'image' => 'fivestar.png',
                'category' => 'Corporations and Non-Cooperative',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 62,
                'name' => 'Genmillers Multipurpose Cooperative',
                'image' => 'genmillogo.jpg',
                'category' => 'General Multipurpose',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 63,
                'name' => 'GLEDCO Multipurpose Cooperative',
                'image' => 'glecologo.png',
                'category' => 'General Multipurpose',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 64,
                'name' => 'Gubat St. Anthony Cooperative',
                'image' => 'gsaclogo.jpeg',
                'category' => 'General Multipurpose',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 65,
                'name' => 'House of Representatives Multi-Purpose Cooperative',
                'image' => 'houseofrep.png',
                'category' => 'Government and Employee',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 66,
                'name' => 'iClick Solutions',
                'image' => 'iCLICK.jpg',
                'category' => 'Corporations and Non-Cooperative',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 67,
                'name' => 'Sunpower Employees MPC',
                'image' => 'image_2023_09_28T08_22_23_671Z.png',
                'category' => 'Corporate and Employee',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 68,
                'name' => 'Lengaoan Indigenous Farmers Multi-Purpose Cooperative',
                'image' => 'image_2023_09_28T08_28_16_265Z.png',
                'category' => 'Community and Farmers',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 69,
                'name' => 'Anabu Development Cooperative',
                'image' => 'image_2023_09_28T08_35_56_781Z (1).png',
                'category' => 'Community and Farmers',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 70,
                'name' => 'Cafe Amadeo Development Cooperative',
                'image' => 'image_2023_09_28T08_36_34_983Z.png',
                'category' => 'Community and Farmers',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 71,
                'name' => 'Oragon Farmers Agriculture Cooperative',
                'image' => 'image_2023_09_28T08_37_17_608Z.png',
                'category' => 'Community and Farmers',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 72,
                'name' => 'Toyota Pasong Tamo Cooperative',
                'image' => 'image_2023_09_28T08_37_54_517Z.png',
                'category' => 'Corporations and Non-Cooperative',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 73,
                'name' => 'Most Holy Rosary Multi-Purpose Cooperative',
                'image' => 'image_2023_09_28T08_38_37_663Z.png',
                'category' => 'Religious and Parish-Based',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 74,
                'name' => 'EMI Employees Development Cooperative',
                'image' => 'image_2023_09_28T08_45_12_864Z.png',
                'category' => 'Corporate and Employee',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 75,
                'name' => 'St. Joseph Parish-Kayapa Multi-Purpose Cooperative',
                'image' => 'image_2023_09_28T09_00_59_264Z.png',
                'category' => 'Religious and Parish-Based',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 76,
                'name' => 'St. Catherine Parish of Nueva Vizcaya Multipurpose Cooperative',
                'image' => 'image_2023_09_28T09_02_06_775Z.png',
                'category' => 'Religious and Parish-Based',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 77,
                'name' => 'Pinagdanlayan Multi-Purpose Cooperative',
                'image' => 'image_2023_09_29T02_12_21_194Z.png',
                'category' => 'Community and Farmers',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 78,
                'name' => 'Isabel Bay Multi-Purpose Cooperative',
                'image' => 'isabelbay.jpg',
                'category' => 'Community and Farmers',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 79,
                'name' => 'Kapalong Cooperative',
                'image' => 'kapalongcoop.jpeg',
                'category' => 'General Multipurpose',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 80,
                'name' => 'Lamac Multi-Purpose Cooperative',
                'image' => 'lamaclogo3.png',
                'category' => 'Community and Farmers',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 81,
                'name' => 'Lamadotrasco Multi-Purpose Cooperative',
                'image' => 'lamadotrasco logo.jpg',
                'category' => 'Community and Farmers',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 82,
                'name' => 'Libagon Area Multi-purpose Cooperative',
                'image' => 'lampcoop.png',
                'category' => 'Community and Farmers',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 83,
                'name' => 'LEYECO V Employees Multipurpose Cooperative',
                'image' => 'leyeco.jpg',
                'category' => 'General Multipurpose',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 84,
                'name' => 'LIGHT Microfinance Inc.',
                'image' => 'lightlogo.jpg',
                'category' => 'General Multipurpose',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 85,
                'name' => 'LIPI Employees Multipurpose Cooperative',
                'image' => 'lipiemco.jpg',
                'category' => 'General Multipurpose',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 86,
                'name' => 'Luntian Multipurpose Cooperative',
                'image' => 'logo luntian mpc.jpg',
                'category' => 'General Multipurpose',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 87,
                'name' => 'Abra Diocesan Teachers and Employees MPC',
                'image' => 'logoadtempco.png',
                'category' => 'Government and Employee',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 88,
                'name' => 'Lyceum of Cebu',
                'image' => 'lyceumlogo.png',
                'category' => 'University/School-Based',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 89,
                'name' => 'Mabini Government Employees Multi-Purpose Cooperative',
                'image' => 'magempuc.png',
                'category' => 'Government and Employee',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 90,
                'name' => 'Malabog Integrated Enterprises Development Cooperative',
                'image' => 'malabogdevcoop.jpg',
                'category' => 'Corporate and Employee',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 91,
                'name' => 'Nestle CDO Employees Multi-Purpose Cooperative',
                'image' => 'nestlecdoempc.png',
                'category' => 'Corporate and Employee',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 92,
                'name' => 'Nexpereon Employees Cooperative',
                'image' => 'nexpereoncoop.png',
                'category' => 'Corporate and Employee',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 93,
                'name' => 'NGPI Multi-Purpose Cooperative',
                'image' => 'ngpimpc.png',
                'category' => 'General Multipurpose',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 94,
                'name' => 'Nabunturan Integrated Cooperative',
                'image' => 'nico.png',
                'category' => 'Community and Farmers',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 95,
                'name' => 'Nuestra Señora De Regla Multipurpose Cooperative',
                'image' => 'nuestrasenoradereglampc.png',
                'category' => 'Religious and Parish-Based',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 96,
                'name' => 'Ozamiz City Peoples Multi-Purpose Cooperative',
                'image' => 'ozamizcooplogo.jpg',
                'category' => 'Community and Farmers',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 97,
                'name' => 'Pera Multipurpose Cooperative',
                'image' => 'peralogo.png',
                'category' => 'General Multipurpose',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 99,
                'name' => 'PHCCI-MPC Tacloban',
                'image' => 'phccitac.png',
                'category' => 'Government and Employee',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 101,
                'name' => 'Sacred Heart Savings Cooperative',
                'image' => 'shsc.jfif',
                'category' => 'Religious and Parish-Based',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 103,
                'name' => 'Southern Leyte Employees Multipurpose Cooperative',
                'image' => 'slemlogo3.png',
                'category' => 'Government and Employee',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 105,
                'name' => 'Cordova Multipurpose Cooperative',
                'image' => 'cmpclogo.png',
                'category' => 'General Multipurpose',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 107,
                'name' => 'DCCPEC Multi-Purpose Cooperative',
                'image' => 'dcocalgo.png',
                'category' => 'General Multipurpose',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 109,
                'name' => 'Mothers and Family Multi-Purpose Cooperative',
                'image' => 'MOFAMCO.jfif',
                'category' => 'Community and Farmers',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 111,
                'name' => 'Online Micro Sellers Multipurpose Cooperative',
                'image' => 'viber_image_2023-04-18_22-20-13-0762.png',
                'category' => 'Market Vendors and Small Business',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 113,
                'name' => 'Pagtambayayong - A Foundation for Mutual Aid, Inc.',
                'image' => 'pagtambanglogo.jpg',
                'category' => 'Community and Farmers',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 115,
                'name' => 'Paknaanon Multi-Purpose Cooperative',
                'image' => 'pamulcologo.png',
                'category' => 'General Multipurpose',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 117,
                'name' => 'Pandan Multi Purpose Cooperative',
                'image' => 'pandanmpc.jpeg',
                'category' => 'General Multipurpose',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 119,
                'name' => 'Parasat Employees Cooperative',
                'image' => 'parasatempc.png',
                'category' => 'Government and Employee',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 121,
                'name' => 'PASAR Employees Multipurpose Cooperative',
                'image' => 'pasarlogo.jpg',
                'category' => 'General Multipurpose',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 123,
                'name' => 'Pilipinhon Multipurpose Cooperative',
                'image' => 'pilicooplogo.jpg',
                'category' => 'General Multipurpose',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 125,
                'name' => 'REC & Co CPAs Certified Public Accountants',
                'image' => 'reccpas.jpg',
                'category' => 'Corporate and Employee',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 127,
                'name' => 'Samal Island Multi-Purpose Cooperative',
                'image' => 'simc.jpg',
                'category' => 'General Multipurpose',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 129,
                'name' => 'San Juan Abra Multi-Purpose Cooperative',
                'image' => 'sanjuanabrampc.jpg',
                'category' => 'General Multipurpose',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 131,
                'name' => 'Sanap Farmers Multi-Purpose Cooperative',
                'image' => 'sanapfarmersmpc.jpg',
                'category' => 'Community and Farmers',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 134,
                'name' => 'Santa Luisa Multi-Purpose Cooperative',
                'image' => 'staluisampc.jpg',
                'category' => 'General Multipurpose',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 137,
                'name' => 'Sapang Palay Mother Mary SMDS Credit Cooperative',
                'image' => 'sapangpalaycoop.png',
                'category' => 'Religious and Parish-Based',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 139,
                'name' => 'Saradit Na Kristyanong Komunidad (SKK) Farmers',
                'image' => 'skk.png',
                'category' => 'Community and Farmers',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 141,
                'name' => 'Seamco Multipurpose Cooperative',
                'image' => 'seamcologo.jpg',
                'category' => 'General Multipurpose',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 143,
                'name' => 'Shangri-La\'s Mactan Multi Purpose Cooperative',
                'image' => 'shangrilalogo.jpeg',
                'category' => 'General Multipurpose',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 145,
                'name' => 'Sibonga Multi-Purpose Cooperative',
                'image' => 'sibongampc.png',
                'category' => 'General Multipurpose',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 147,
                'name' => 'Silago Multi-Purpose Cooperative',
                'image' => 'silagologo.png',
                'category' => 'General Multipurpose',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 149,
                'name' => 'Socorro Empowered Peoples Cooperative',
                'image' => 'soemcologo.png',
                'category' => 'Community and Farmers',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 151,
                'name' => 'SRDP Consulting Inc.',
                'image' => 'srdp.png',
                'category' => 'Corporations and Non-Cooperative',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 153,
                'name' => 'St Luke\'s Medical Center Multi Purpose Cooperative',
                'image' => 'stlukeslogo.png',
                'category' => 'Corporate and Employee',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 155,
                'name' => 'St. John the Baptist SMDS Credit Cooperative',
                'image' => 'stjohnthebaptistcoop.jpg',
                'category' => 'Religious and Parish-Based',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 157,
                'name' => 'Sta. Maria Dela Strada Multi-purpose Cooperatives',
                'image' => 'smds logo.jpg',
                'category' => 'Religious and Parish-Based',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 159,
                'name' => 'Sta. Monica of Bustos Multi-Purpose Cooperative',
                'image' => 'stamonicaofbustos.jpg',
                'category' => 'Community and Farmers',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 161,
                'name' => 'Tagum City Employees Multipurpose Cooperative',
                'image' => 'tacempco.png',
                'category' => 'Government and Employee',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 163,
                'name' => 'Telecommunication Employee\'s Multipurpose Cooperative',
                'image' => 'telemcologo2.png',
                'category' => 'Corporate and Employee',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 165,
                'name' => 'The Real Alternative Investment Multi-Purpose Cooperative',
                'image' => 'cooptoday.jpeg',
                'category' => 'General Multipurpose',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 167,
                'name' => 'Triple 2 Agri-Industrial Corporation',
                'image' => 't2aicorp.jpg',
                'category' => 'Community and Farmers',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 169,
                'name' => 'Upland Rural Bank of Dalaguete',
                'image' => 'uplandlogo.png',
                'category' => 'Community and Farmers',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 171,
                'name' => 'USP Multi Purpose Cooperative',
                'image' => 'cooptoday.jpeg',
                'category' => 'General Multipurpose',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 173,
                'name' => 'Xavier University Community Credit Cooperative',
                'image' => 'xucccologo.png',
                'category' => 'University, School-Based',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        foreach ($imagedsData as $data) {
            DB::table('imageds')->insert($data);
        }
    }
}